# Change these first
owner: mobilitysol # Your GitHub organization or username, where this repository lives
repo: monitorweb # The name of this repository

sites:
    - name: Server Mobility Produccion
      url: https://mobilitysol.com:20443
    - name: Server Mobility Testing
      url: https://mobilitysol.com:30443
    - name: Mobility Solutions Web
      url: https://mobilitysol.com
    - name: Nextcloud Clip Uruguay
      url: https://clip.interclip.com/nextcloud
    - name: Zulip Uruguay
      url: https://zulip.mobilitysol.com:2443/
    - name: Clip Connections Web
      url: https://www.interclip.com
    - name: Registro de visitas Clip Uruguay
      url: http://clip.interclip.com:8123/kimai2/public
    - name: PizzaPiedra Web
      url: https://pizzapiedra.com.uy
    - name: RequetePizza Web
      url: https://requetepizza.com
    - name: PizzaRiing Web
      url: https://pizzariing.uy
    - name: PizzaTime Web
      url: https://pizzatime.uy
    - name: Asian Food
      url: https://asianfood.com.uy
      

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /monitorweb
  logoUrl: https://www.mobilitysol.com/firmas/logo_simple.png
  name: Monitor Web Mobility
  introTitle: "**Upptime** es el Monitor de estado open-source utilizado por **Mobility Solutions**."
  introMessage: Esta pagina de estado utiliza **real-time** data desde  GitHub. [**Obtenelo Gratis**](https://github.com/upptime/upptime)
  navbar:
    - title: Mobility Solutions
      href: https://mobilitysol.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
