# Change these first
owner: mobilitysol # Your GitHub organization or username, where this repository lives
repo: monitorweb # The name of this repository

sites:
    - name: Mobility Solutions
      url: https://mobilitysol.com
    - name: Clip Connections
      url: https://www.interclip.com
    - name: Wildfly 20
      url: https://mobilitysol.com:20443
    - name: Wildfly 30
      url: https://mobilitysol.com:30443
    - name: Nextcloud Uruguay
      url: https://clip.interclip.com/nextcloud
    - name: Zulip Uruguay
      url: https://zulip.mobilitysol.com:2443/
    - name: Git Mobility
      url: https://git.mobilitysol.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /monitorweb
  logoUrl: https://www.mobilitysol.com/firmas/logo_simple.png
  name: Monitor Web Mobility
  introTitle: "**Upptime** es el Monitor de estado open-source utilizado por **Mobility Solutions**."
  introMessage: Esta pagina de estado utiliza **real-time** data desde  [GitHub repository](https://github.com/upptime/upptime). [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Mobility Solutions
      href: https://mobilitysol.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
